language: rust

rust:
# TODO: test on stable/beta when aesni crate works with stdsimd
#  - stable
#  - beta
  - nightly

script:
  - rustc --version --verbose
  - cargo --version --verbose
  - cargo build --verbose # ensure project builds without mockhsm feature
  - cargo test --verbose --features=mockhsm

branches:
  only:
    - master

