language: rust

rust:
# TODO: test on stable/beta when aesni crate works with stdsimd
#  - stable
#  - beta
  - nightly

script:
  - rustc --version --verbose
  - cargo --version --verbose
  - cargo test --features mockhsm

branches:
  only:
    - master

