[package]
name          = "yubihsm"
description   = "Pure Rust client for YubiHSM2 devices"
version       = "0.18.1" # Also update html_root_url in lib.rs when bumping this
license       = "Apache-2.0 OR MIT"
authors       = ["Tony Arcieri <tony@iqlusion.io>"]
documentation = "https://docs.rs/yubihsm"
homepage      = "https://github.com/tendermint/yubihsm-rs"
repository    = "https://github.com/tendermint/yubihsm-rs/tree/master/"
readme        = "README.md"
categories    = ["cryptography"]
keywords      = ["ed25519", "hmac", "hsm", "signing", "yubikey"]

[badges]
circle-ci = { repository = "tendermint/yubihsm-rs" }

[dependencies]
aes = "0.3"
bitflags = "1"
block-modes = "0.2"
byteorder = "1.2"
cmac = "0.2"
failure = "0.1"
failure_derive = "0.1"
hmac = { version = "0.7", optional = true }
lazy_static = { version = "1", optional = true }
libusb = { version = "0.3", optional = true }
log = "0.4"
pbkdf2 = { version = "0.3", optional = true }
rand = "0.5"
serde = "1.0"
serde_derive = "1.0"
ring = { version = "0.13", optional = true }
sha2 = { version = "0.8", optional = true }
subtle = "1"
untrusted = { version = "0.6", optional = true }
uuid = { version = "0.7", default-features = false, features = ["v4"] }
zeroize = "0.3"

[dev-dependencies]
criterion = "0.2"
lazy_static = "1"
ring = "0.13"
untrusted = "0.6"

[features]
default = ["http", "passwords"]
http = []
mockhsm = ["passwords", "ring", "untrusted"]
nightly = ["subtle/nightly", "zeroize/nightly"]
passwords = ["hmac", "pbkdf2", "sha2"]
rsa = ["sha2"]
usb = ["lazy_static", "libusb"]

[package.metadata.docs.rs]
features = ["mockhsm", "rsa", "usb"]
rustc-args = ["-Ctarget-feature=+aes"]

[[bench]]
name = "ed25519"
harness = false
