[package]
name        = "yubihsm-client"
description = "Pure Rust client for YubiHSM2 devices"
version     = "0.0.0"
license     = "MIT/Apache-2.0"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
homepage    = "https://github.com/tarcieri/yubihsm-client"
readme      = "README.md"
categories  = ["cryptography"]
keywords    = ["cryptography", "encryption", "security"]

[dependencies]
aesni = "0.2"
byteorder = "1.2"
clear_on_drop = "0.2"
cmac = "0.1"
constant_time_eq = "0.1"
failure = "0.1"
failure_derive = "0.1"
hmac = "0.4"
pbkdf2 = "0.1"
rand = "0.4"
reqwest = "0.8"
sha2 = "0.6"
tiny_http = { version = "0.5", optional = true }

[features]
default = []
mockhsm = ["tiny_http"]
