[package]
name          = "yubihsm"
description   = "Pure Rust client for YubiHSM2 devices"
version       = "0.10.1" # Also update html_root_url in lib.rs when bumping this
license       = "MIT OR Apache-2.0"
authors       = ["Tony Arcieri <bascule@gmail.com>"]
documentation = "https://docs.rs/yubihsm"
homepage      = "https://github.com/tendermint/yubihsm-rs"
repository    = "https://github.com/tendermint/yubihsm-rs/tree/master/"
readme        = "README.md"
categories    = ["cryptography"]
keywords      = ["cryptography", "encryption", "security"]

[badges]
circle-ci = { repository = "tendermint/yubihsm-rs" }

[dependencies]
aes = "0.1"
bitflags = "1.0"
block-modes = "0.1"
byteorder = "1.2"
clear_on_drop = "0.2"
cmac = "0.1"
constant_time_eq = "0.1"
failure = "0.1"
failure_derive = "0.1"
hmac = "0.6"
pbkdf2 = "0.2"
rand = "0.4"
serde = "1.0"
serde_derive = "1.0"
ring = { version = "0.13.0-alpha5", optional = true }
sha2 = "0.7"
untrusted = { version = "0.6", optional = true }
uuid = { version = "0.6", features = ["v4"] }

[features]
aes-soft = ["aes/force_soft"]
bench = []
default = []
integration = ["ring", "untrusted"]
mockhsm = ["integration"]
nightly = ["clear_on_drop/nightly"]

[package.metadata.docs.rs]
features = ["mockhsm"]
rustc-args = ["-Ctarget-feature=+aes"]
