[package]
name        = "yubihsm-client"
description = "Pure Rust client for YubiHSM2 devices"
version     = "0.0.0"
license     = "MIT/Apache-2.0"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
homepage    = "https://github.com/tendermint/yubihsm-client"
readme      = "README.md"
categories  = ["cryptography"]
keywords    = ["cryptography", "encryption", "security"]

[dependencies]
aesni = "0.2"
bitflags = "1.0"
block-modes = "0.1"
byteorder = "1.2"
clear_on_drop = "0.2"
cmac = "0.1"
constant_time_eq = "0.1"
ed25519-dalek = { version = "= 0.6.0", optional = true, features = ["sha2"] }
failure = "0.1"
failure_derive = "0.1"
hmac = "0.4"
pbkdf2 = "0.1"
rand = "0.4"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
sha2 = "0.6"
tiny_http = { version = "0.5", optional = true }

[features]
default = []
dalek = ["ed25519-dalek"]
mockhsm = ["dalek", "tiny_http"]
