[package]
name          = "yubihsm"
description   = "Pure Rust client for YubiHSM2 devices"
version       = "0.5.0" # Also update html_root_url in lib.rs when bumping this
license       = "MIT/Apache-2.0"
authors       = ["Tony Arcieri <bascule@gmail.com>"]
documentation = "https://docs.rs/yubihsm"
homepage      = "https://github.com/tendermint/yubihsm-rs"
repository    = "https://github.com/tendermint/yubihsm-rs/tree/master/"
readme        = "README.md"
categories    = ["cryptography"]
keywords      = ["cryptography", "encryption", "security"]

[badges]
circle-ci = { repository = "tendermint/yubihsm-rs" }

[dependencies]
aesni = "0.3"
bitflags = "1.0"
block-modes = "0.1"
byteorder = "1.2"
clear_on_drop = "0.2"
cmac = "0.1"
constant_time_eq = "0.1"
ed25519-dalek = { version = "= 0.6.0", optional = true, features = ["sha2"] }
failure = "0.1"
failure_derive = "0.1"
hmac = "0.4"
pbkdf2 = "0.1"
rand = "0.4"
reqwest = { version = "0.8", optional = true }
serde = "1.0"
serde_derive = "1.0"
sha2 = "0.6"

[features]
bench = []
default = ["reqwest-connector"]
dalek = ["ed25519-dalek"]
mockhsm = ["dalek"]
reqwest-connector = ["reqwest"]

[package.metadata.docs.rs]
features = ["reqwest-connector", "mockhsm"]
rustc-args = ["-Ctarget-feature=+aes"]
