[package]
name        = "yubihsm-client"
description = "Pure Rust client for YubiHSM2 devices"
version     = "0.0.0"
license     = "MIT/Apache-2.0"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
homepage    = "https://github.com/tarcieri/yubihsm-client"
readme      = "README.md"
categories  = ["cryptography"]
keywords    = ["cryptography", "encryption", "security"]

[dependencies]
byteorder = "1.2"
failure = "0.1"
failure_derive = "0.1"
scp03 = { path = "scp03" }
reqwest = "0.8"
tiny_http = { version = "0.5", optional = true }

[features]
default = []
mockhsm = ["tiny_http"]
