version: 2

jobs:
  build:
    docker:
    - image: tendermint/kms:build-2019-06-05-v0 # bump cache keys when modifying this
    environment:
      RUSTFLAGS: -D warnings
    steps:
    - checkout
    - restore_cache:
        key: cache-2019-06-05-v0 # bump save_cache key below too
    - run:
        name: Install Rust 1.36.0 # TODO: update Rust in the upstream Docker image
        command: |
          rustup toolchain install 1.36.0
          rustup default 1.36.0
          rustup component add rustfmt
          rustup component add clippy
    - run:
        name: rustfmt
        command: |
          cargo fmt --version
          cargo fmt -- --check
    - run:
        name: clippy
        command: |
          cargo clippy --version
          cargo clippy --features=yolocrypto,secp256k1,usb
          cargo clippy --features=mockhsm
    - run:
        name: build --no-default-features
        command: |
          rustc --version
          cargo --version
          cargo build --no-default-features
    - run:
        name: build --no-default-features --features=passwords
        command: |
          rustc --version
          cargo --version
          cargo build --no-default-features --features=passwords
    - run:
        name: build --benches
        command: |
          rustc --version
          cargo --version
          cargo build --benches
    - run:
        name: build --release
        command: |
          rustc --version
          cargo --version
          cargo build --release
    - run:
        name: build --features=usb
        command: |
          rustc --version
          cargo --version
          cargo build --features=usb
    - run:
        name: build --features=usb --release
        command: |
          rustc --version
          cargo --version
          cargo build --features=usb --release
    - run:
        name: build --all-features --examples
        command: |
          rustc --version
          cargo --version
          cargo build --all-features --examples
    - run:
        name: test
        command: |
          rustc --version
          cargo --version
          cargo test --features=mockhsm,secp256k1,yolocrypto
    - run:
        name: audit
        command: |
          cargo audit --version
          cargo audit
    - save_cache:
        key: cache-2019-06-05-v0 # bump restore_cache key above too
        paths:
        - "~/.cargo"
        - "./target"
