version: 2

jobs:
  build:
    docker:
    - image: tendermint/kms:build-2019-01-24-v0 # bump cache keys when modifying this

    steps:
    - checkout
    - restore_cache:
        key: cache-2018-11-27-v0 # bump save_cache key below too
    - run:
        name: rustfmt
        command: |
          cargo fmt --version
          cargo fmt -- --check
    - run:
        name: clippy
        command: |
          cargo clippy --version
          cargo clippy --features=rsa-preview,secp256k1,usb
          cargo clippy --features=mockhsm
    - run:
        name: build --no-default-features
        command: |
          rustc --version
          cargo --version
          cargo build --no-default-features
    - run:
        name: build --no-default-features --features=passwords
        command: |
          rustc --version
          cargo --version
          cargo build --no-default-features --features=passwords
    - run:
        name: build --benches
        command: |
          rustc --version
          cargo --version
          cargo build --benches
    - run:
        name: build --release
        command: |
          rustc --version
          cargo --version
          cargo build --release
    - run:
        name: build --features=rsa-preview
        command: |
          rustc --version
          cargo --version
          cargo build --features=rsa-preview
    - run:
        name: build --features=usb
        command: |
          rustc --version
          cargo --version
          cargo build --features=usb
    - run:
        name: build --features=usb --release
        command: |
          rustc --version
          cargo --version
          cargo build --features=usb --release
    - run:
        name: test
        command: |
          rustc --version
          cargo --version
          cargo test --features=mockhsm,rsa-preview,secp256k1
    - run:
        name: audit
        command: |
          cargo audit --version
          cargo audit
    - save_cache:
        key: cache-2018-11-27-v0 # bump restore_cache key above too
        paths:
        - "~/.cargo"
        - "./target"
