version: 2

jobs:
  build:
    docker:
      - image: iqlusion/rust-ci:201804090 # bump cache keys when modifying this

    steps:
      - checkout
      - restore_cache:
          key: cache-201804090 # bump save_cache key below too
      - run:
          name: rustfmt
          command: |
            rustup run $RUST_NIGHTLY_VERSION rustfmt --version
            rustup run $RUST_NIGHTLY_VERSION cargo fmt -- --write-mode=diff
      - run:
          name: clippy
          command: |
            rustup run $RUST_NIGHTLY_VERSION cargo clippy --version
            rustup run $RUST_NIGHTLY_VERSION cargo clippy --features=mockhsm
      - run:
          name: build --no-default-features (nightly-2018-04-05)
          command: |
            rustup run $RUST_NIGHTLY_VERSION rustc --version
            rustup run $RUST_NIGHTLY_VERSION cargo --version
            rustup run $RUST_NIGHTLY_VERSION cargo build --no-default-features
      - run:
          name: build (nightly-2018-04-05)
          command: |
            rustup run $RUST_NIGHTLY_VERSION rustc --version
            rustup run $RUST_NIGHTLY_VERSION cargo --version
            rustup run $RUST_NIGHTLY_VERSION cargo build
      - run:
          name: test (nightly-2018-04-05)
          command: |
            rustup run $RUST_NIGHTLY_VERSION cargo test --features=mockhsm
      - save_cache:
          key: cache-201804090 # bump restore_cache key above too
          paths:
            - "~/.cargo"
            - "./target"
